Repository ThugMS/GameLab_W07, pull requests merged in 2023-09, with the labels that each got.

#4 [Feat] : 보스 돌진 패턴까지 구현
  Assets/Scenes/MS.unity
  Assets/Scenes/MS.unity.meta
  Assets/Scripts/Monster/DefensiveBoss.cs
  Assets/Scripts/Monster/DefensiveBoss.cs.meta
  Assets/Scripts/Monster/MonsterBase.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: 민석, Feat

#7 [Feat] : 방패 sortingLayer 동적변경
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Scenes/MS.unity
  Assets/Scripts/Monster/DefensiveBoss.cs
  Assets/Scripts/Monster/MonsterBase.cs
Labels: 민석, Feat

#8 [Feat] : 보스 그림자 패턴까지 구현 완료
  Assets/Prefabs/Monster.meta
  Assets/Prefabs/Monster/DefensiveBoss.meta
  Assets/Prefabs/Monster/DefensiveBoss/DefensiveBoss.prefab
  Assets/Prefabs/Monster/DefensiveBoss/DefensiveBoss.prefab.meta
  Assets/Prefabs/Monster/DefensiveBoss/DefensiveBossFire.prefab
  Assets/Prefabs/Monster/DefensiveBoss/DefensiveBossFire.prefab.meta
  Assets/Prefabs/Monster/DefensiveBoss/Shadow.prefab
  Assets/Prefabs/Monster/DefensiveBoss/Shadow.prefab.meta
  Assets/Scenes/MS.unity
  Assets/Scripts/Monster/DefensiveBoss.cs
  Assets/Scripts/Monster/MonsterBase.cs
  Assets/Scripts/Monster/Shadow.cs
  Assets/Scripts/Monster/Shadow.cs.meta
  Assets/Scripts/Monster/Slime.cs
Labels: 민석, Feat

#9 [Feat] : 보스 반사 기믹 완성
  Assets/Animation/Monster.meta
  Assets/Animation/Monster/ReflectEffect.anim
  Assets/Animation/Monster/ReflectEffect.anim.meta
  Assets/Animation/Monster/Renderer.controller
  Assets/Animation/Monster/Renderer.controller.meta
  Assets/Prefabs/Monster/DefensiveBoss/DefensiveBoss.prefab
  Assets/Prefabs/Monster/DefensiveBoss/ReflectProjectile.prefab
  Assets/Prefabs/Monster/DefensiveBoss/ReflectProjectile.prefab.meta
  Assets/Scenes/MS.unity
  Assets/Scripts/Monster/DefensiveBoss.cs
  Assets/Scripts/Monster/Reflect.cs
  Assets/Scripts/Monster/Reflect.cs.meta
  Assets/Scripts/Monster/ReflectProjectile.cs
  Assets/Scripts/Monster/ReflectProjectile.cs.meta
  Assets/Scripts/Player/Arrow.cs
  Assets/Sprites/Monster.meta
  Assets/Sprites/Monster/Gravity-SpriteSheet.png
  Assets/Sprites/Monster/Gravity-SpriteSheet.png.meta
Labels: 민석, Feat

#11 feat: 불릿타임 추가
  Assets/Animation/Feather.meta
  Assets/Animation/Feather/Charging.anim
  Assets/Animation/Feather/Charging.anim.meta
  Assets/Animation/Feather/Warp Feather.controller
  Assets/Animation/Feather/Warp Feather.controller.meta
  Assets/Materials/RippleMaterial.mat
  Assets/Materials/RippleMaterial.mat.meta
  Assets/Materials/Unlit Mat.mat
  Assets/Materials/Unlit Mat.mat.meta
  Assets/Prefabs/Player.meta
  Assets/Prefabs/Player/Arrow.prefab
  Assets/Prefabs/Player/Arrow.prefab.meta
  Assets/Prefabs/Player/Player.prefab
  Assets/Prefabs/Player/Player.prefab.meta
  Assets/Prefabs/Player/Ripple Effect.prefab
  Assets/Prefabs/Player/Ripple Effect.prefab.meta
  Assets/Prefabs/Player/Warp Feather.prefab
  Assets/Prefabs/Player/Warp Feather.prefab.meta
  Assets/Resources/PlayerInput.cs
  Assets/Resources/PlayerInput.inputactions
  Assets/Scenes/JW.meta
  Assets/Scenes/JW.unity
  Assets/Scenes/JW/Global Volume Profile.asset
  Assets/Scenes/JW/Global Volume Profile.asset.meta
  Assets/Scripts/Effects.meta
  Assets/Scripts/Effects/RippleEffect.cs
  Assets/Scripts/Effects/RippleEffect.cs.meta
  Assets/Scripts/Managers.meta
  Assets/Scripts/Managers/CameraManager.cs
  Assets/Scripts/Managers/CameraManager.cs.meta
  Assets/Scripts/Player/Bow.cs
  Assets/Scripts/Player/Player.cs
  Assets/Scripts/Player/PlayerAim.cs
  Assets/Scripts/Player/PlayerBulletTime.cs
  Assets/Scripts/Player/PlayerBulletTime.cs.meta
  Assets/Scripts/Player/PlayerDash.cs
  Assets/Scripts/Player/PlayerMove.cs
  Assets/Scripts/Player/PlayerWarp.cs
  Assets/Scripts/Player/PlayerWarp.cs.meta
  Assets/Settings/Renderer2D.asset
  Assets/Shaders.meta
  Assets/Shaders/RealRippleShader.shadergraph
  Assets/Shaders/RealRippleShader.shadergraph.meta
  Assets/Shaders/Unlit Mat.shadergraph
  Assets/Shaders/Unlit Mat.shadergraph.meta
  Assets/Sprites/feather.png
  Assets/Sprites/feather.png.meta
  ProjectSettings/GraphicsSettings.asset
Labels: 정우, Feat

#13 feat: 플레이어 수정
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Materials/Particle Mat.mat
  Assets/Materials/Particle Mat.mat.meta
  Assets/Materials/Ripple Material.mat
  Assets/Materials/Ripple Material.mat.meta
  Assets/Materials/Unlit Mat.mat
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Prefabs/Player/Arrow.prefab
  Assets/Prefabs/Player/Player.prefab
  Assets/Prefabs/Player/Warp Feather.prefab
  Assets/Scenes/JW.unity
  Assets/Scenes/JW/Global Volume Profile.asset
  Assets/Scripts/Effects/RippleEffect.cs
  Assets/Scripts/Player/Arrow.cs
  Assets/Scripts/Player/PlayerBulletTime.cs
  Assets/Scripts/Player/PlayerWarp.cs
  Assets/Shaders/Particle Shader.shadergraph
  Assets/Shaders/Particle Shader.shadergraph.meta
Labels: 정우, Feat

#14 [Feat] 슬라임 애니메이션 최종
  Assets/Animation/Slime.meta
  Assets/Animation/Slime/FireSlime.controller
  Assets/Animation/Slime/FireSlime.controller.meta
  Assets/Animation/Slime/FireSlimeDie.anim
  Assets/Animation/Slime/FireSlimeDie.anim.meta
  Assets/Animation/Slime/FireSlimeIdle.anim
  Assets/Animation/Slime/FireSlimeIdle.anim.meta
  Assets/Animation/Slime/FireSlimeMove.anim
  Assets/Animation/Slime/FireSlimeMove.anim.meta
  Assets/FireSlimeMoveAnimation.cs
  Assets/FireSlimeMoveAnimation.cs.meta
  Assets/Prefabs/Monster/Slime.meta
  Assets/Prefabs/Monster/Slime/Slime.prefab
  Assets/Prefabs/Monster/Slime/Slime.prefab.meta
  Assets/Scenes/MK.unity
  Assets/Scripts/Monster/Slime.cs
  Assets/Sprites/Monster/Fire Elemental Sprite Sheet.png
  Assets/Sprites/Monster/Fire Elemental Sprite Sheet.png.meta
Labels: 민경, Feat

#15 [Feat] : 보스 패턴 간략하게 완성
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Prefabs/Monster/DefensiveBoss/ReflectProjectile.prefab
  Assets/Scenes/MS.meta
  Assets/Scenes/MS.unity
  Assets/Scripts/Monster/DefensiveBoss.cs
  Assets/Scripts/Monster/Reflect.cs
  Assets/Scripts/Monster/ReflectProjectile.cs
Labels: 민석, Feat

#16 [Feat] 타일맵 수정, Spike 레이어 추가, 슬라임 충돌
  Assets/Prefabs/Tilemap.prefab
  Assets/Scenes/MK.unity
  Assets/Scripts/Monster/Slime.cs
  ProjectSettings/TagManager.asset
Labels: 민경, Feat

#17 [Feat] : 보스 콜라이더 처리 완료
  Assets/Prefabs/Monster/DefensiveBoss/DefensiveBoss.prefab
  Assets/Scenes/MS.unity
  Assets/Scripts/Monster/DefensiveBoss.cs
  Assets/Scripts/Monster/MonsterBase.cs
  Assets/Scripts/Player/Arrow.cs
  ProjectSettings/TagManager.asset
Labels: 민석, Feat

#19 [Fix] : 슬라임 움직임 수정 중
  Assets/Scripts/Monster/Slime.cs
Labels: 민석, Fix

#20 [Feat] : 화살 관통 삭제
  Assets/Scripts/Player/Arrow.cs
Labels: 민석, Feat

#22 fix: 화살 사라지는 버그 수정
  Assets/Prefabs/Player/Arrow.prefab
Labels: 정우, Fix

#25 Jw
  Assets/Animation/UIHeart/Die.anim
  Assets/Animation/UIHeart/Heart.controller
  Assets/Prefabs/UI/Global Volume.prefab
  Assets/Prefabs/UI/Global Volume.prefab.meta
  Assets/Prefabs/UI/Main Camera.prefab
  Assets/Prefabs/UI/Main Camera.prefab.meta
  Assets/Scenes/JW.unity
  Assets/Scripts/Player/PlayerDeadEye.cs
  Assets/Scripts/Player/PlayerHp.cs
  Assets/Scripts/UI/UIGauge.cs
  Assets/Scripts/UI/UIHeart.cs
  Assets/Scripts/UI/UIHeartContainer.cs
  Assets/Scripts/UI/UIVIgnette.cs
Labels: 정우, Feat

#26 [Feat] : HP바 구현
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Scenes/MS.unity
  Assets/Scripts/Monster/DefensiveBoss.cs
  Assets/Scripts/Monster/DefensiveBossHP.cs
  Assets/Scripts/Monster/DefensiveBossHP.cs.meta
  Assets/Scripts/Monster/MonsterBase.cs
  Assets/Scripts/Monster/Slime.cs
Labels: 민석, Feat

#27 [Feat] : 보스 UI 프리팹화
  Assets/Prefabs/Monster/DefensiveBoss/BossHP.prefab
  Assets/Prefabs/Monster/DefensiveBoss/BossHP.prefab.meta
  Assets/Prefabs/Monster/DefensiveBoss/DefensiveBoss.prefab
Labels: 민석, Feat

#28 [Feat] 튜토2 타일맵
  Assets/Prefabs/Monster/Slime/Slime.prefab
  Assets/Prefabs/Tilemap.prefab
  Assets/Scenes/MK.unity
  Assets/Scripts/Monster/MonsterSpawn.cs
  Assets/Scripts/Monster/MonsterSpawn.cs.meta
Labels: 민경, Feat

#29 feat: 깃털 따라다니기 및 불릿타임 버그 수정
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Prefabs/Player/Player.prefab
  Assets/Prefabs/Player/Warp Feather.prefab
  Assets/Scripts/Player/Player.cs
  Assets/Scripts/Player/PlayerWarp.cs
  Assets/Scripts/Player/WarpFeather.cs
  Assets/Scripts/Player/WarpFeather.cs.meta
Labels: 정우, Feat, Fix

#30 feat: 플레이어 초기화 함수 추가
  Assets/Scripts/Player/Player.cs
  Assets/Scripts/Player/PlayerDeadEye.cs
Labels: 정우, Feat

#33 [Feat] : SpawnPoint 모두 설정 완료
  Assets/Prefabs/Tilemap.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Tutorial2SpawnTrigger.cs
  Assets/Scripts/Tutorial2SpawnTrigger.cs.meta
Labels: 민석, Feat

#34 feat: 플레이어 피격 무적 추가
  Assets/AllIn1SpriteShader/Materials/Renderer.mat
  Assets/AllIn1SpriteShader/Materials/Renderer.mat.meta
  Assets/Prefabs/Player/Player.prefab
  Assets/Scenes/JW.unity
  Assets/Scripts/Player/Body.cs
  Assets/Scripts/Player/Player.cs
Labels: 정우, Feat

#36 1
  Assets/Prefabs/Player/Player.prefab
Labels: 정우, Fix

#37 [Feat] : 스테이지 초기화 관리
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Scenes/Main.unity
  Assets/Scripts/MapSpawinTrigger.cs
  Assets/Scripts/Monster/MonsterBase.cs
  Assets/Scripts/Monster/ReflectProjectile.cs
  Assets/Scripts/Tutorial1SpawnTrigger.cs
Labels: 민석, Feat

#39 [Feat] : 보스 초기세팅 그폰하면 초기화 되게 구현
  Assets/Scripts/MapSpawinTrigger.cs
  Assets/Scripts/Monster/DefensiveBoss.cs
Labels: 민석, Feat

#41 [Fix] : 전체 연결 완료
  Assets/Prefabs/Monster/DefensiveBoss/Shadow.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/MapSpawinTrigger.cs
  Assets/Scripts/Monster/DefensiveBoss.cs
  Assets/Scripts/Monster/Shadow.cs
  Assets/Scripts/Player/Player.cs
Labels: 민석, Feat

#42 [Feat] : 진짜 다 연결
  Assets/Button.cs
Labels: 민석, Feat

#43 fix: Init시 모든 동작 ForceQuit.
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Scripts/Player/Player.cs
  Assets/Scripts/Player/PlayerStat.cs
  Assets/Scripts/Player/PlayerWarp.cs
Labels: 정우, Fix

#45 fix: 대쉬 삭제
  Assets/Scripts/Player/Player.cs
Labels: 정우, Fix

#47 fix: 데드아이 초기값 수정
  Assets/Scripts/Player/PlayerDeadEye.cs
Labels: 정우, Fix

#48 [Fix] : 보스 커맨드 수정
  Assets/Scripts/Monster/DefensiveBoss.cs
Labels: 민석, Fix
