Repository ThugMS/GameLab_W07, pull requests merged in 2023-10, with the labels that each got.

#53 [Fix] : 테스트용 코드 수정
  Assets/Scenes/MS/MainTest.unity
  Assets/Scenes/MS/MainTest.unity.meta
  Assets/Scripts/MapSpawinTrigger.cs
  Assets/Scripts/Monster/ThugBoss2.cs
  Assets/Scripts/Monster/ThugBoss2.cs.meta
  Assets/Scripts/Tutorial1SpawnTrigger.cs
Labels: 민석, Fix

#54 [Fix] : 테스트 코드 다시 수정
  Assets/Scripts/MapSpawinTrigger.cs
  Assets/Scripts/Tutorial1SpawnTrigger.cs
Labels: Fix

#55 [Feat] ThugBoss 페이즈1
  Assets/Prefabs/Monster/ThugBoss.meta
  Assets/Prefabs/Monster/ThugBoss/Bullet.prefab
  Assets/Prefabs/Monster/ThugBoss/Bullet.prefab.meta
  Assets/Scripts/Monster/ThugBoss.cs
  Assets/Scripts/Monster/ThugBoss.cs.meta
  Assets/Scripts/Monster/ThugBossBullet.cs
  Assets/Scripts/Monster/ThugBossBullet.cs.meta
  Assets/Scripts/Monster/ThugBossPhase1.cs
  Assets/Scripts/Monster/ThugBossPhase1.cs.meta
Labels: 민경, Feat

#57 feat: 평타를 깃털로 교체
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Prefabs/Player/Arrow.prefab
  Assets/Prefabs/Player/Player.prefab
  Assets/Prefabs/Player/Warp Feather.prefab
  Assets/Resources/PlayerInput.cs
  Assets/Resources/PlayerInput.inputactions
  Assets/Scenes/Main.unity
  Assets/Scripts/Managers/CameraManager.cs
  Assets/Scripts/Monster/Reflect.cs
  Assets/Scripts/Player/Arrow.cs
  Assets/Scripts/Player/Bow.cs
  Assets/Scripts/Player/Player.cs
  Assets/Scripts/Player/PlayerAim.cs
  Assets/Scripts/Player/PlayerBulletTime.cs
  Assets/Scripts/Player/PlayerMove.cs
Labels: 정우, Feat

#59 feat: 자야
  Assets/Materials/Particle Mat.mat
  Assets/Materials/Unlit Mat.mat
  Assets/Prefabs/Player/Arrow.prefab
  Assets/Prefabs/Player/Warp Feather.prefab
  Assets/Scripts/Player/Arrow.cs
  Assets/Scripts/Player/Bow.cs
  Assets/Sprites/feather2.png
  Assets/Sprites/feather2.png.meta
Labels: 정우, Feat

#61 [Feat ]: 보스 레이저 패턴 구현
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/Animation/Monster/Laser.anim
  Assets/Animation/Monster/Laser.anim.meta
  Assets/Animation/Monster/Laser.controller
  Assets/Animation/Monster/Laser.controller.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Prefabs/Monster/ThugBoss/Laser.prefab
  Assets/Prefabs/Monster/ThugBoss/Laser.prefab.meta
  Assets/Scenes/MS/MainTest.unity
  Assets/Scripts/Monster/Laser.cs
  Assets/Scripts/Monster/Laser.cs.meta
  Assets/Scripts/Monster/ThugBossPhase2.cs
Labels: 민석, Feat

#63 [Feat] : 보스 합치기 플레이어 공격 가능
  Assets/Prefabs/Monster/ThugBoss/Boss2.prefab
  Assets/Prefabs/Monster/ThugBoss/Boss2.prefab.meta
  Assets/Prefabs/Player/Player.prefab
  Assets/Scenes/MS/MainTest.unity
Labels: 민석, Feat

#64 feat: 자야 완성
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Materials/Particle Mat.mat
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Prefabs/Player/Player.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Player/Arrow.cs
Labels: 정우, Feat

#68 Minseok
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Animation/Monster/Body.controller
  Assets/Animation/Monster/Move.anim
  Assets/Animation/Monster/Move.anim.meta
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Prefabs/Monster/ThugBoss/Boss2.prefab
  Assets/Scenes/MS/MainTest.unity
  Assets/Scripts/Monster/ThugBoss.cs
  Assets/Scripts/Monster/ThugBossPhase2.cs
Labels: 민석, Feat

#69 fix: 불릿타임 점수 타격시 획득
  Assets/Prefabs/Player/Player.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Player/Arrow.cs
Labels: 정우, Fix

#70 [Fix] 보스 무한생성 오류 수정..
  Assets/Scripts/MapSpawinTrigger.cs
  Assets/Scripts/Monster/ThugBoss.cs
  Assets/Scripts/Monster/ThugBossPhase1.cs
Labels: 민경, Fix

#71 [Fix] : 탄환 뚝뚞 끊기는 현상 수정
  Assets/Prefabs/Monster/ThugBoss/Boss2.prefab
  Assets/Prefabs/Monster/ThugBoss/Bullet.prefab
  Assets/Scenes/MS/MainTest.unity
  Assets/Scripts/Monster/Rock.cs
  Assets/Scripts/Player/PlayerBulletTime.cs
Labels: 민석, Feat

#73 feat: 장전방식 엔터 더 건전 방식으로 변화
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Scripts/Player/Arrow.cs
  Assets/Scripts/Player/Player.cs
  Assets/Scripts/Player/PlayerAim.cs
Labels: 정우, Feat

#74 fix: 회수시 추가 데미지
  Assets/Scripts/Player/Arrow.cs
Labels: 정우, Fix

#75 [Feat] 플레이어 죽으면 존재하는 탄막 삭제
  Assets/Prefabs/Tilemap.prefab
  Assets/Scripts/MapSpawinTrigger.cs
  Assets/Scripts/Monster/ThugBoss.cs
  Assets/Scripts/Monster/ThugBossPhase1.cs
Labels: 민경, Feat

#76 fix: 불릿타임시 데드아이 회복 방지
  Assets/Scripts/Player/PlayerBulletTime.cs
  Assets/Scripts/Player/PlayerDeadEye.cs
Labels: 정우, Fix

#77 [Feat] 총알 부모 바꾸기
  Assets/Prefabs/Bullets.prefab
  Assets/Prefabs/Bullets.prefab.meta
  Assets/Prefabs/Monster/ThugBoss/Boss2.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Monster/ThugBoss.cs
  Assets/Scripts/Monster/ThugBossPhase1.cs
Labels: 민경, Feat

#79 feat: 리콜 게이지 추가
  Assets/AllIn1SpriteShader/Materials/Fill_2.mat
  Assets/AllIn1SpriteShader/Materials/Fill_2.mat.meta
  Assets/Prefabs/Player/Player.prefab
  Assets/Scripts/Player/Arrow.cs
  Assets/Scripts/Player/Bow.cs
  Assets/Scripts/Player/Player.cs
  Assets/Scripts/Player/PlayerAim.cs
  Assets/Scripts/Player/RecallGauge.cs
  Assets/Scripts/Player/RecallGauge.cs.meta
Labels: 정우, Feat

#80 [Feat]: 보스 스폰위치 수정
  Assets/Prefabs/Tilemap.prefab
  Assets/Scenes/MS/MainTest.unity
  Assets/Scripts/Player/PlayerBulletTime.cs
Labels: 민석, Feat

#82 [Feat] : 쇠사슬 묶인거 구현
  Assets/Prefabs/Monster/ThugBoss/Boss2.prefab
  Assets/Sprites/Monster/ThugBoss/BodyShackle.png
  Assets/Sprites/Monster/ThugBoss/BodyShackle.png.meta
  Assets/Sprites/Monster/ThugBoss/Shackle.png
  Assets/Sprites/Monster/ThugBoss/Shackle.png.meta
Labels: 민석, Feat

#84 feat: 돌아오는 화살 이펙트 추가
  Assets/Materials/Particle Mat Red.mat
  Assets/Materials/Particle Mat Red.mat.meta
  Assets/Prefabs/Player/Recall Hit Effect.prefab
  Assets/Prefabs/Player/Recall Hit Effect.prefab.meta
  Assets/Prefabs/UI/Effect Manager.prefab
  Assets/Prefabs/UI/Effect Manager.prefab.meta
  Assets/Scenes/MS/MainTest.unity
  Assets/Scripts/Effects/EffectManager.cs
  Assets/Scripts/Effects/EffectManager.cs.meta
  Assets/Scripts/Player/Arrow.cs
  Assets/Scripts/UI/UIGauge.cs
Labels: 정우, Feat

#86 fix: 불릿타임 키 스페이스바로
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Resources/PlayerInput.cs
  Assets/Resources/PlayerInput.inputactions
Labels: 정우, Fix

#88 [Fix] 보스 페이즈1 밸런싱, 불릿타임 수정
  Assets/Prefabs/Monster/ThugBoss/Boss2.prefab
  Assets/Prefabs/Player/Player.prefab
Labels: 민경

#89 [Fix] : 밸런스 수정
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package-2021.2+.unitypackage.meta
  Assets/AllIn1SpriteShader/2DRenderer-URP-Package.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Attribute Processors.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Custom Drawers.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Sample - RPG Editor.unitypackage.meta
  Assets/Prefabs/Monster/ThugBoss/Boss2.prefab
  Assets/Scenes/MS/MainTest.unity
Labels: 민석, Feat

#90 Minseok
  Assets/Animation/Monster/Laser.anim
  Assets/Scenes/MS/MainTest.unity
Labels: 민석, Fix

#91 [Fix] : 보스 피통수정
  Assets/Scenes/MS/MainTest.unity
Labels: 민석, Fix

#93 [Feat] : 죽으면 bullet도 모두 사라지도록 수정
  Assets/Scenes/MS/MainTest.unity
  Assets/Scripts/Monster/Rock.cs
  Assets/Scripts/Monster/ThugBossPhase2.cs
Labels: 민석, Feat
